### ISSUE TITLE
cannot find generator

### ISSUE THREAD

**Issue by Skeyelab** [github/github-ds#10]
Anyone seen this error?  Any advice?

```
$ rails generate github:kv:active_record
Expected boolean default value for '--markerb'; got :erb (string)
Expected string default value for '--controller'; got false (boolean)
Could not find generator 'github:kv:active_record'. Maybe you meant 'github:d_s:active_record', 'active_record:model' or 'active_record:devise'
Run `rails generate --help` for more options.```

**Comment by jnunemaker** [comment]
Ah, this is a docs issue due to renaming the gem several times. It should be `rails generate github:ds:active_record`. Can you try that and let me know if it doesn't fix your issue?

**Comment by taenw** [comment]
I'm having the same issue. I ran `rails generate github:ds:active_record`
and got this: 
```
Could not find generator 'github:ds:active_record'. Maybe you meant 'github:d_s:active_record', 'ahoy:stores:active_record' or 'active_record:model'
Run rails generate --help for more options.
```
I ran `github:d_s:active_record` and it gives the same error.
I also ran `rails generate --help` and `github:d_s:active_record` is included under github.

**Comment by jnunemaker** [comment]
Ugh. It does look like rails is dropping an underscore in there. I'll look into it.

**Comment by jnunemaker** [comment]
@taenw fixed https://github.com/github/github-ds/issues/16.

**Comment by taenw** [comment]
Confirms that it does work now. Thanks!
