### ISSUE TITLE
serviceworker.js

### ISSUE THREAD

**Issue by laelyona** [github/github-ds#13]
when i try to run ;- rails g serviceworker:install
Expected boolean default value for '--markerb'; got :erb (string)
Could not find generator '--markerb'. Maybe you meant 'mailer', 'erb:mailer' or 'uploader'
Run `rails generate --help` for more options.
please help?

**Comment by jnunemaker** [comment]
@laelyona I think you created this issue on the wrong repo. This repo is for github-ds which is a collection of sql tools on top of active record. It has nothing to do with service workers.
