### ISSUE TITLE
NameError: uninitialized constant Github

### ISSUE THREAD

**Issue by lizdeika** [github/github-ds#27]
Whatever I do I get this error
Rails 5.1
ruby 2.4.1

tried
require manually
variants
```ruby
require 'github/ds'
require 'github/sql'
```
```ruby
require 'github/sql'
```
```ruby
require 'github/ds.rb'
require 'github/sql.rb'
```

none helps

**Comment by jnunemaker** [comment]
The constant is `GitHub` with a capital H. Use that and you should be good.
