### ISSUE TITLE
Question: How to convert to current timezone?

### ISSUE THREAD

**Issue by rmonteiro89** [github/github-ds#41]
Hi there,

I am having some trouble to convert UTC to current time zone in the specific code below:
```
    sql = GitHub::SQL.new <<-SQL
      SELECT
        DATE(some_datetime::TIMESTAMPTZ AT TIME ZONE '#{Time.zone.tzinfo.name}') as custom_date,
        COUNT(id) as total_count
      FROM ( #{query} ) AS receivable
      GROUP BY custom_date
      ORDER BY custom_date
    SQL

    sql.results
```

We are using PostgreSQL and store all the dates in UTC without time zone.

When I get the results, the date is in UTC and not in the current timezone.

Any idea of what I could do?

**Comment by jnunemaker** [comment]
Have you tried the :force_timezone option? You can pass :utc or :local to it. I wonder if because you are doing the time zone manipulation server side if you need `force_timezone: :local` like:

```ruby
    sql = GitHub::SQL.new <<-SQL, force_timezone: :local
      SELECT
        DATE(some_datetime::TIMESTAMPTZ AT TIME ZONE '#{Time.zone.tzinfo.name}') as custom_date,
        COUNT(id) as total_count
      FROM ( #{query} ) AS receivable
      GROUP BY custom_date
      ORDER BY custom_date
    SQL

    sql.results
```

I didn't look in depth and I've always just returned utc times from the server. Let me know if that doesn't help.

**Comment by rmonteiro89** [comment]
Thank you so much for your reply. I dont think this problem is related to this gem, because even doing it with pure SQL didnt work. Gonna try to figure out something else, probably I am missing something. Gonna close this for now. Thank you again.
