### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jnunemaker** [github/github-ds#64]
Can we get a new release of this? I'd be happy to be on the repo again and help maintain it. I was the original releaser from GitHub back in the day so I'm not just some rando off the street. 😄

**Comment by jnunemaker** [comment]
FWIW, I've been locking to git sources at refs but it would be nice to get a gem release. Worst case I can work and rename to something else.

**Comment by zerowidth** [comment]
😎 

`v0.5.3` is released and pushed to rubygems.org

**Comment by jnunemaker** [comment]
@zerowidth baller! Thanks.
