### ISSUE TITLE
Get ruby 2.4 in matrix for travis

### ISSUE THREAD

**Issue by jnunemaker** [github/github-ds#7]
Example failed job on travis: https://travis-ci.org/github/github-ds/jobs/221026610. The issue is: `gem install mysql -v '2.9.1'`. Probably an easy fix, just need to take a sec and look at it.

**Comment by eugeneius** [comment]
See https://github.com/luislavena/mysql-gem/pull/32 - the `mysql` gem doesn't currently work on Ruby 2.4.
